spring:
  datasource:
    username: hiss
    password: 5QyFXcuks!cMdk4
    url: jdbc:postgresql://amvera-hiss-cnpg-leon-postgres-rw:5432/leondb
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  #    open-in-view: false
  graphql:
    cors:
      allowed-origins: http://localhost:8081
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    host: smtp.leon-studio.ru
    port: 587
    username: leon@leon-studio.ru
    password: nB7nQ9eN3xqP4dC4

telegram:
  bot:
    token: 7341574913:AAHycVDUhoarPx-AZc99VzbkdbM-fJCFLBI
  chat:
    id: -1002225238036
iqsms:
  login: f1722934271657
  password: 487982